export const metadata = {
  title: 'IMDB',
  description: 'Generated by using next js and tailwind css',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
      {children}
      </body>
    </html>
  )
}
