import Header from "../components/Header";
import Providers from "./Providers";
export const metadata = {
  title: "IMDb",
  description: "Generated by using next js and tailwind css",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>      
          {/* Header */}
          <Header />
          {/* Navbar */}
          {/* SearchBox */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
